# Generated by Django 6.0.1 on 2026-01-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('date_lost', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
