# Generated by Django 6.0.1 on 2026-01-30 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_lostitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='item',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='LostItem',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('found', 'Found'), ('lost', 'Lost')], max_length=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.item'),
        ),
        migrations.AddField(
            model_name='claim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FoundItem',
        ),
        migrations.DeleteModel(
            name='ClaimRequest',
        ),
    ]
